# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: $RESOLVED_VERSION
tag-template: $RESOLVED_VERSION
version-template: $MAJOR.$MINOR.$PATCH

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: 💥 Breaking changes
    labels: 
      - breaking
  - title: 🚨 Removed
    label: removed
  - title: 🎉 Major features and improvements
    labels:
      - major-enhancement
  - title: 🐛 Major bug fixes
    labels:
      - major-bug
  - title: ⚠️ Deprecated
    label: deprecated
  - title: 🚀 New features and improvements
    labels:
      - enhancement
      - feature
      - rfe
  - title: 🐛 Bug fixes
    labels:
      - bug
      - fix
      - bugfix
      - regression
  - title: 👷 Changes for developers
    labels:
      - developer 
  # Default label used by Dependabot
  - title: 📦 Dependency updates
    label: dependencies
  - title: 📝 Documentation updates
    label: documentation
  - title: 👻 Maintenance
    labels: 
      - chore
      - internal
  - title: 🚦 Tests
    labels: 
      - test
      - tests
exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog
  - invalid

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
      - 'removed'
      - 'deprecated'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'major-enhancement'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'major-bug'
      - 'bug'
      - 'bugfix'
      - 'fix'
      - 'developer'
      - 'internal'
      - 'test'
      - 'tests'
  default: patch

template: |
  <!-- Optional: add a release summary here -->
  $CHANGES
  - search: '@dependabot-preview'
    replace: '@dependabot'

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
